hosts: [{name: "host1", user: "user1", pass: "4r9NwaQBt1T3L17XzDw9FNg55k4mP7ZoKdwZwKN3NLA="},
        {name: "host2", user: "user2", pass: "4r9NwaQBt1T3L17XzDw9FNg55k4mP7ZoKdwZwKN3NLA="}]
env: [{name: " ", value: " "},
      {name: " ", value: " "}]
serverpass: "4r9NwaQBt1T3L17XzDw9FNg55k4mP7ZoKdwZwKN3NLA="
heartbeat_timeout: 30
init_timeout: 40
poll_timeout: 20
hostErrors: 3
hostJobs: 1